spring:
  datasource:
    url: jdbc:mysql://localhost:3306/code_push?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
  data:
    redis:
      host: localhost
      port: 6380
      password: 123456
      database: 0
      timeout: 3000
ai:
  registry:
    # 心跳检测配置
    heartbeat:
      interval: 5000  # 心跳间隔(ms)
      timeout: 20000  # 心跳超时(ms)
      max-retry: 3    # 最大重试次数
    
    # 服务发现配置
    discovery:
      cache-refresh-interval: 10000  # 缓存刷新间隔(ms)
      push-empty-protection: true     # 空保护
    
    # 负载均衡配置
    loadbalancer:
      default-rule: round-robin  # 默认负载均衡策略
      health-check-enabled: true # 启用健康检查